// Generated by CoffeeScript 1.6.1
(function() {
  var Gravity, InitialFrame, InitialRotation;

  InitialRotation = require("./InitialRotation");

  Gravity = require("./Gravity");

  InitialFrame = (function() {
    var applyXYZ, calcAccel, calcRotation, normalAccel;

    function InitialFrame(accelValues, gyroValues, timestamp) {
      this.gAccel = accelValues;
      this.accelAndGrav = calcAccel.call(this);
      this.gyro = gyroValues;
      this.rotation = calcRotation.call(this);
      this.accel = normalAccel.call(this);
      this.timestamp = timestamp;
      this.timeDelta = 0;
      this.endVelocity = [0, 0, 0];
      this.positionDelta = [0, 0, 0];
      this.position = [0, 0, 0];
    }

    normalAccel = function() {
      var inNED;
      inNED = this.rotation.rotate(this.accelAndGrav);
      return [inNED[0], inNED[1], inNED[2] + Gravity];
    };

    calcAccel = function() {
      var times9_8;
      times9_8 = function(coord) {
        return this.gAccel[coord] * Gravity;
      };
      return applyXYZ.call(this, times9_8);
    };

    calcRotation = function() {
      return new InitialRotation(this.accelAndGrav);
    };

    applyXYZ = function(fcn) {
      return [0, 1, 2].map(fcn, this);
    };

    return InitialFrame;

  })();

  module.exports = InitialFrame;

}).call(this);
