// Generated by CoffeeScript 1.6.1
(function() {
  var MPU6050, mpu;

  MPU6050 = require("./MPU6050");

  mpu = new MPU6050;

  setInterval(function() {
    return mpu.read(function(err, result) {
      return console.log(result);
    });
  }, 200);

}).call(this);
