// Generated by CoffeeScript 1.6.1
(function() {
  var Tracker, tracker;

  Tracker = require("./PositionTracker");

  tracker = new Tracker(50);

  tracker.on("data", function(frame) {
    console.log(frame.accel);
    console.log(frame.gyro);
    console.log(frame.position);
    return console.log('----------');
  });

  tracker.start();

}).call(this);
