// Generated by CoffeeScript 1.6.1
(function() {
  var app, connect, fs, io, server;

  connect = require("connect");

  app = connect().use(connect["static"]("vendor")).use(connect["static"]("public"));

  server = app.listen(process.env.port || 3000);

  io = require("socket.io").listen(server);

  fs = require("fs");

  io.set("log level", 1);

}).call(this);
